# SwiftLint Configuration for Hogwarts iOS
# https://github.com/realm/SwiftLint

excluded:
  - DerivedData
  - .build
  - Pods
  - Packages

line_length:
  warning: 150
  error: 200
  ignores_comments: true
  ignores_urls: true

type_body_length:
  warning: 400
  error: 600

function_body_length:
  warning: 60
  error: 100

file_length:
  warning: 700
  error: 1000

disabled_rules:
  - trailing_comma
  - opening_brace
  - todo
  - nesting
  - identifier_name

opt_in_rules:
  - closure_spacing
  - empty_count
  - force_unwrapping
  - implicit_return
  - sorted_imports
