name: Hogwarts
options:
  bundleIdPrefix: org.databayt
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "6.0"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
    INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
    INFOPLIST_KEY_UILaunchScreen_Generation: YES
    INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
    INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
    INFOPLIST_KEY_NSCameraUsageDescription: "Camera access is needed for QR code attendance check-in"
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor

packages:
  GoogleSignIn:
    url: https://github.com/google/GoogleSignIn-iOS
    from: "7.0.0"
  FacebookLogin:
    url: https://github.com/facebook/facebook-ios-sdk
    from: "16.0.0"

targets:
  Hogwarts:
    type: application
    platform: iOS
    sources:
      - path: hogwarts
        excludes:
          - "**/.DS_Store"
    resources:
      - path: hogwarts/resources
        excludes:
          - "**/.DS_Store"
    info:
      path: hogwarts/resources/Info.plist
      properties:
        CFBundleDisplayName: Hogwarts
        CFBundleName: Hogwarts
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSCameraUsageDescription: "Camera access is needed for QR code attendance check-in"
        ITSAppUsesNonExemptEncryption: false
        GIDClientID: "GOOGLE_CLIENT_ID"
        CFBundleURLTypes:
          - CFBundleURLSchemes:
              - "com.googleusercontent.apps.GOOGLE_CLIENT_ID"
              - "fb$(FACEBOOK_APP_ID)"
        FacebookAppID: "$(FACEBOOK_APP_ID)"
        FacebookClientToken: "$(FACEBOOK_CLIENT_TOKEN)"
        FacebookDisplayName: Hogwarts
    entitlements:
      path: hogwarts/resources/Hogwarts.entitlements
      properties:
        com.apple.developer.applesignin:
          - Default
        keychain-access-groups:
          - $(AppIdentifierPrefix)org.databayt.Hogwarts
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: org.databayt.Hogwarts
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: YES
        ENABLE_PREVIEWS: YES
    dependencies:
      - package: GoogleSignIn
      - package: FacebookLogin
        product: FacebookLogin

  HogwartsTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: HogwartsTests
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: Hogwarts

  HogwartsUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: HogwartsUITests
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: Hogwarts

schemes:
  Hogwarts:
    build:
      targets:
        Hogwarts: all
        HogwartsTests: [test]
        HogwartsUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - HogwartsTests
        - HogwartsUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
